/**
 * Universal Analyzer v2 - Core Type Definitions
 *
 * These types define the interfaces for the plugin-based analyzer architecture.
 */

import * as ts from "typescript";
import type { BusinessImpact } from "../../types.js";

// ============================================================================
// Detection Types
// ============================================================================

/**
 * A detection represents a pattern found by a detector plugin.
 * It may or may not be a violation - that's determined by the ContractMatcher.
 */
export interface Detection {
  /** Name of the plugin that made this detection */
  pluginName: string;

  /** Pattern type (e.g., 'property-chain', 'event-listener', 'throwing-function') */
  pattern: string;

  /** The AST node where the pattern was detected */
  node: ts.Node;

  /** Package name (e.g., 'axios', '@prisma/client') */
  packageName: string;

  /** Function name (e.g., 'get', 'user.create', 'on:error') */
  functionName: string;

  /** Confidence level of the detection */
  confidence: "high" | "medium" | "low";

  /** Additional metadata specific to the pattern */
  metadata: Record<string, any>;
}

/**
 * A violation represents a confirmed contract violation.
 * Generated by the ContractMatcher after matching a detection to a contract.
 */
export interface Violation {
  /** Source file path */
  file: string;

  /** Line number (1-indexed) */
  line: number;

  /** Column number (1-indexed) */
  column: number;

  /** Package name */
  package: string;

  /** Function name */
  function: string;

  /** Postcondition ID from contract */
  postconditionId: string;

  /** Severity level */
  severity: "error" | "warning";

  /** Human-readable violation message */
  message: string;

  /** Code context (lines around violation) — JSON-encoded {lines: [{line, content, highlighted}]} */
  codeContext: string;

  /** Line number of the first line in codeContext snippet (1-indexed) */
  codeContextStartLine?: number;

  /** Whether the violation is inside a try-catch block */
  inTryCatch: boolean;

  /** Whether the violation was suppressed */
  suppressed: boolean;

  /** Reason for suppression (if suppressed) */
  suppressionReason?: string;

  /**
   * Stable fingerprint for this violation.
   * sha256("{package}:{postconditionId}:{normalizedFile}:{line}:{callExpression}").slice(0, 32)
   * Matches the fingerprint computed by the SaaS, enabling cross-referencing
   * between CLI suppressions and SaaS violation records.
   */
  fingerprint?: string;

  /** The call expression text (e.g. "readFile") — used in fingerprint computation */
  callExpression?: string;

  /**
   * Business impact from the matched postcondition.
   * Surfaces counterfactual value to users: what this would have caused in production.
   */
  business_impact?: BusinessImpact;

  /**
   * Additional postconditions violated at the same call site.
   * Listed so the developer/AI can write a complete fix in one pass,
   * rather than discovering requirements incrementally across scan runs.
   */
  subViolations?: Array<{
    postconditionId: string;
    message: string;
    severity: "error" | "warning";
  }>;
}

// ============================================================================
// Plugin System Types
// ============================================================================

/**
 * Context provided to detector plugins during analysis.
 * Contains shared resources like type checker, symbol table, etc.
 */
export interface PluginContext {
  /** TypeScript type checker for symbol resolution */
  typeChecker: ts.TypeChecker;

  /** Map of symbol names to their symbols */
  symbolTable: Map<string, ts.Symbol>;

  /** Map of imports (import name -> import info) */
  importMap: Map<string, ImportInfo>;

  /** Control flow analyzer */
  controlFlow: ControlFlowAnalyzer;

  /** Source file being analyzed */
  sourceFile: ts.SourceFile;

  /** Program (for multi-file analysis) */
  program: ts.Program;
}

/**
 * Context specific to a single AST node during traversal.
 */
export interface NodeContext extends PluginContext {
  /** Current node being visited */
  node: ts.Node;

  /** Parent node */
  parent?: ts.Node;

  /** Depth in AST (0 = root) */
  depth: number;
}

/**
 * Import information tracked during analysis.
 */
export interface ImportInfo {
  /** Package name (e.g., 'axios', '@prisma/client') */
  packageName: string;

  /** Imported name (e.g., 'axios', 'PrismaClient', 'get') */
  importedName: string;

  /** Import kind */
  kind: "default" | "named" | "namespace" | "side-effect";

  /** Original name in package (for renamed imports) */
  originalName?: string;

  /** Import declaration node */
  declaration: ts.ImportDeclaration;
}

/**
 * Control flow analyzer interface.
 * Provides methods to analyze control flow (try-catch, conditionals, etc.)
 */
export interface ControlFlowAnalyzer {
  /** Check if a node is inside a try-catch block */
  isInTryCatch(node: ts.Node): boolean;

  /** Get the enclosing try statement, if any */
  getEnclosingTry(node: ts.Node): ts.TryStatement | undefined;

  /** Get the enclosing block (function, if, loop, etc.) */
  getEnclosingBlock(node: ts.Node): ts.Block | undefined;

  /** Check if a node is in a conditional branch */
  isInConditional(node: ts.Node): boolean;

  /**
   * Check if a node is inside an if-block guarded by response.ok or response.status.
   * Recognizes the idiomatic fetch/undici pattern where status is checked BEFORE .json().
   */
  isNodeInsideResponseOkGuard(node: ts.Node): boolean;
}

// ============================================================================
// Detector Plugin Interface
// ============================================================================

/**
 * Base interface for all detector plugins.
 * Plugins implement event handlers for different AST node types.
 */
export interface DetectorPlugin {
  /** Unique plugin name */
  name: string;

  /** Plugin version (semver) */
  version: string;

  /** Optional plugin description */
  description?: string;

  // -------------------------
  // Lifecycle Hooks
  // -------------------------

  /**
   * Called once when plugin is registered.
   * Use this to initialize plugin state.
   */
  initialize?(context: PluginContext): void;

  /**
   * Called before traversal of each source file.
   * Use this to reset per-file state.
   */
  beforeTraversal?(sourceFile: ts.SourceFile, context: PluginContext): void;

  /**
   * Called after traversal of each source file.
   * Use this to finalize detections or cleanup.
   */
  afterTraversal?(detections: Detection[], context: PluginContext): void;

  // -------------------------
  // Event Handlers (Node Visitors)
  // -------------------------

  /**
   * Called for every call expression.
   * Examples: foo(), obj.method(), new Class()
   */
  onCallExpression?(node: ts.CallExpression, context: NodeContext): Detection[];

  /**
   * Called for every property access expression.
   * Examples: obj.prop, obj.prop.nested
   */
  onPropertyAccess?(
    node: ts.PropertyAccessExpression,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every variable declaration.
   * Examples: const x = ..., let y = ..., var z = ...
   */
  onVariableDeclaration?(
    node: ts.VariableDeclaration,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every return statement.
   * Examples: return x, return foo()
   */
  onReturnStatement?(
    node: ts.ReturnStatement,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every arrow function or function expression.
   * Examples: () => {}, function() {}
   */
  onFunctionExpression?(
    node: ts.ArrowFunction | ts.FunctionExpression,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every identifier.
   * Examples: variable names, function names
   */
  onIdentifier?(node: ts.Identifier, context: NodeContext): Detection[];

  /**
   * Called for every binary expression.
   * Examples: a + b, x === y
   */
  onBinaryExpression?(
    node: ts.BinaryExpression,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every conditional expression.
   * Examples: condition ? a : b
   */
  onConditionalExpression?(
    node: ts.ConditionalExpression,
    context: NodeContext,
  ): Detection[];

  /**
   * Called for every tagged template expression.
   * Examples: sql`SELECT * FROM users`, html`<div>...</div>`
   */
  onTaggedTemplateExpression?(
    node: ts.TaggedTemplateExpression,
    context: NodeContext,
  ): Detection[];
}

// ============================================================================
// Contract Matching Types
// ============================================================================

/**
 * A contract loaded from the corpus.
 */
export interface Contract {
  /** Package name */
  package: string;

  /** Semver range */
  semver: string;

  /** Contract version */
  contract_version: string;

  /** Maintainer */
  maintainer: string;

  /** Last verified date */
  last_verified: string;

  /** Contract status */
  status: "production" | "draft" | "deprecated";

  /** Functions with postconditions */
  functions: FunctionContract[];
}

/**
 * A function contract with postconditions.
 */
export interface FunctionContract {
  /** Function name (may include dots for property chains) */
  name: string;

  /** Import path */
  import_path: string;

  /** Description */
  description: string;

  /** Postconditions (error behaviors) */
  postconditions: Postcondition[];

  /** Optional edge cases */
  edge_cases?: EdgeCase[];
}

/**
 * A postcondition defines an error behavior.
 */
export interface Postcondition {
  /** Unique ID */
  id: string;

  /** Condition when this behavior applies */
  condition: string;

  /** Error type thrown */
  throws: string;

  /** Required handling description */
  required_handling: string;

  /** Source documentation */
  source: string;

  /** Severity */
  severity: "error" | "warning";

  /** Optional suppressions */
  suppressions?: Suppression[];
}

/**
 * Edge case documentation.
 */
export interface EdgeCase {
  /** Unique ID */
  id: string;

  /** Description */
  description: string;

  /** Source documentation */
  source: string;

  /** Severity */
  severity: "error" | "warning";
}

/**
 * Suppression rule for false positive prevention.
 */
export interface Suppression {
  /** Pattern to suppress */
  pattern: string;

  /** Reason for suppression */
  reason: string;

  /** How to detect this pattern */
  detection: string;
}

/**
 * Result of matching a detection to a contract.
 */
export interface ContractMatch {
  /** The matched contract */
  contract: Contract;

  /** The matched function */
  function: FunctionContract;

  /** The matched postcondition */
  postcondition: Postcondition;

  /** Confidence of the match (0-1) */
  confidence: number;
}

// ============================================================================
// Analysis Result Types
// ============================================================================

/**
 * Result of analyzing a single source file.
 */
export interface FileAnalysisResult {
  /** File path */
  file: string;

  /** Detections made in this file */
  detections: Detection[];

  /** Violations found in this file */
  violations: Violation[];

  /** Analysis duration (ms) */
  duration: number;

  /** Errors encountered during analysis */
  errors: AnalysisError[];
}

/**
 * Result of analyzing an entire project.
 */
export interface ProjectAnalysisResult {
  /** Project root path */
  projectPath: string;

  /** Total files analyzed */
  filesAnalyzed: number;

  /** Total detections */
  totalDetections: number;

  /** Total violations */
  totalViolations: number;

  /** Per-file results */
  files: FileAnalysisResult[];

  /** Aggregate statistics */
  statistics: AnalysisStatistics;

  /** Total duration (ms) */
  duration: number;
}

/**
 * Analysis statistics.
 */
export interface AnalysisStatistics {
  /** Violations by package */
  byPackage: Map<string, number>;

  /** Violations by severity */
  bySeverity: Map<"error" | "warning", number>;

  /** Violations by file */
  byFile: Map<string, number>;

  /** Detections by plugin */
  byPlugin: Map<string, number>;
}

/**
 * Error encountered during analysis.
 */
export interface AnalysisError {
  /** Error message */
  message: string;

  /** File where error occurred */
  file?: string;

  /** Line number (if applicable) */
  line?: number;

  /** Stack trace */
  stack?: string;
}

// ============================================================================
// Analyzer Configuration
// ============================================================================

/**
 * Configuration for the universal analyzer.
 */
export interface AnalyzerConfig {
  /** Path to tsconfig.json */
  tsConfigPath: string;

  /** Path to corpus directory */
  corpusPath: string;

  /** Paths to analyze (if not all files in tsconfig) */
  includePaths?: string[];

  /** Paths to exclude */
  excludePaths?: string[];

  /** Whether to include test files (*.spec.ts, *.test.ts, *.e2e-spec.ts, etc.) */
  includeTests?: boolean;

  /** Whether to include draft contracts */
  includeDrafts?: boolean;

  /** Plugins to enable (if empty, all plugins are enabled) */
  enabledPlugins?: string[];

  /** Plugin-specific configuration */
  pluginConfig?: Map<string, any>;

  /** Performance options */
  performance?: {
    /** Max memory usage (MB) */
    maxMemory?: number;

    /** Enable incremental analysis */
    incremental?: boolean;

    /** Cache directory for incremental analysis */
    cacheDir?: string;
  };
}
