/**
 * Expected test output for with-inline-suppression.ts
 *
 * Auto-generated by: npm run test:fixtures:generate
 * Do not edit manually - regenerate when analyzer or contracts change
 */

import type { ExpectedViolations } from '../../../types/index.js';

export const expected: ExpectedViolations = {
  "fixtures": "with-inline-suppression.ts",
  "expectations": [
    {
      "id": "get-error-violations",
      "description": "ERROR violations in get",
      "functionName": "get",
      "minViolations": 2,
      "expectedClauses": [
        "error-4xx-5xx",
        "rate-limited-429"
      ],
      "severity": "error",
      "approximateLines": [
        12,
        12
      ]
    }
  ],
  "summary": {
    "expectedErrorCount": {
      "min": 2,
      "max": 2
    },
    "expectedWarningCount": {
      "min": 0,
      "max": 0
    },
    "expectedInfoCount": {
      "min": 0,
      "max": 0
    }
  }
};
